language: scala
scala:
- 2.10.2
deploy:
  provider: heroku
  api_key:
    secure: nJExaq//7AhahLg0c8H4VCQ7ftkI5n+3FcO5/lq8kRpgCABIO/YScTlLABUDTFKeTkB21ga7tbpkCkUb97OXBmTDejXa/gqrc9Rodre38KrFkPUtp3M9QlUL220YvFY1nIDkTAZUp+2FrF1PonMhxmWaA0+AJ95CmjLqkPsK4AM=
  app: scala-vienna-prod
  on:
    repo: scala-vienna/scala-vienna-web
MEETUP_API_KEY:
  secure: qUTGe1d/hdYGtAq/H/oWpYmSf3wUvME6wopDTlMQaOUIrnUEtwHVbZ/w6W1bgjYwJLDH4o9pyn5lw25ICM+tWyj7ChldAlOGDWYp8P14UP/6MZyogL2psHc7aKbXncRd6WTlGHr8kYamxGDsCUuFYcVqRIQXmZSv4o0rw8Yn5e8=
GITHUB_API_KEY:
  secure: TGg7eioNdIZ/ccWHMlbSuo1qOswoYlcDE9h8HSVLyHEEFvGVYuFCs1NHgJLP+6uT95RgVWkBE1fIE7aEQ/m2JPB4i8VrON7OjIXSHHrbgLRMWc3ECrNWX8uAu/BG9FaAHNUKvvBpvi+jy8Ckxd9R7g5pfR9jZ04x9wdMl5FAyGI=
